# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_rest', '0003_bibleverse_verse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleverse',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
