# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 04:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BibleChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_rest.BibleBook')),
            ],
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='BibleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='bible_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_rest.BibleVersion'),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_rest.BibleBook'),
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_rest.BibleChapter'),
        ),
        migrations.AddField(
            model_name='biblebook',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible_rest.BibleVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='biblechapter',
            unique_together=set([('number', 'book')]),
        ),
    ]
