# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblebook',
            name='version',
        ),
        migrations.AlterUniqueTogether(
            name='biblechapter',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='biblechapter',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bibleverse',
            name='bible_version',
        ),
        migrations.AddField(
            model_name='bibleverse',
            name='version',
            field=models.CharField(default='ESV', max_length=20),
        ),
        migrations.AlterField(
            model_name='bibleverse',
            name='book',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bibleverse',
            name='chapter',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='BibleBook',
        ),
        migrations.DeleteModel(
            name='BibleChapter',
        ),
        migrations.DeleteModel(
            name='BibleVersion',
        ),
    ]
