# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_rest', '0002_auto_20160523_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleverse',
            name='verse',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
