# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible_rest', '0004_auto_20160523_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibleverse',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='bibleverse',
            unique_together=set([('version', 'book', 'chapter', 'verse')]),
        ),
    ]
